### 1 - 1

Загрузите данные о расходах из файла /datasets/ad_data.csv и сохраните в переменной ad_data. Информацию о регистрациях получите из файла /datasets/site_data.csv и сохраните в переменной site_data.

Объедините данные таблиц в один датафрейм по столбцу date. 

Сохраните результат в переменной funnel (англ. «воронка») и выведите первые 5 строк получившегося датасета.

In [5]:
import pandas as pd

In [6]:
ad_data = pd.read_csv('./ad_data.csv')

site_data = pd.read_csv('./site_data.csv') 

funnel = ad_data.merge(site_data, on='date')

funnel.head(5)

         date  impressions  clicks  registrations
0  2019-08-01         6153      61              6
1  2019-08-02         8254      81              6
2  2019-08-03         4434      43              4
3  2019-08-04         9510      79              7
4  2019-08-05         7167      70              6

### 1 - 2

Посчитайте CTR и CR воронки. Результаты сохраните в столбцах funnel['ctr, %'] и funnel['cr, %'] соответственно. Выведите первые 5 строк датафрейма.

In [7]:
funnel['ctr, %'] = (funnel['clicks'] / funnel['impressions']) * 100

In [8]:
funnel['cr, %'] = (funnel['registrations'] / funnel['clicks']) * 100

In [9]:
funnel.head(5)

         date  impressions  clicks  registrations    ctr, %     cr, %
0  2019-08-01         6153      61              6  0.991386  9.836066
1  2019-08-02         8254      81              6  0.981342  7.407407
2  2019-08-03         4434      43              4  0.969779  9.302326
3  2019-08-04         9510      79              7  0.830705  8.860759
4  2019-08-05         7167      70              6  0.976699  8.571429

### 2 - 1

Найдите значения CTR и CR по неделям.
Загрузите данные о ежедневных конверсиях из файла /datasets/funnel_daily.csv и сохраните в переменной funnel_daily. Переведите значения столбца funnel_daily['date'] в формат datetime. Добавьте столбец funnel_daily['week'], в котором посчитайте номер недели для соответствующей даты.
Посчитайте понедельный CTR и CR. Результат сохраните в переменной funnel_weekly.

In [10]:
funnel_daily = pd.read_csv('./funnel_daily.csv')

In [11]:
funnel_daily['date'] = pd.to_datetime(funnel_daily['date'])

In [12]:
# Извлечение номера недели
funnel_daily['week'] = funnel_daily['date'].dt.isocalendar().week

In [13]:
funnel_weekly = funnel_daily.groupby('week')[['impressions','clicks','registrations' ]].sum()
funnel_weekly['ctr, %'] = (funnel_weekly['clicks'] / funnel_weekly['impressions']) * 100 
funnel_weekly['cr, %'] = funnel_weekly['registrations']/funnel_weekly['clicks'] * 100

In [14]:
funnel_weekly.head()

      impressions  clicks  registrations    ctr, %     cr, %
week
31          28351     264             23  0.931184  8.712121
32          57031     503             43  0.881976  8.548708
33          57184     471             39  0.823657  8.280255
34          49911     424             37  0.849512  8.726415
35          34956     307             25  0.878247  8.143322

### 2 - 2

Аналогично решению прошлой задачи составьте дневные, недельные и месячные воронки.

Прочитайте данные о расходах на рекламу /datasets/ad_data_2.csv и сохраните в переменной ad_data. Данные о регистрациях: /datasets/site_data_2.csv — в переменной site_data.

Методом merge() объедините ad_data и site_data по столбцу 'date'. Сохраните полученный датафрейм с дневными воронками в переменной funnel_daily. В funnel_daily создайте столбцы 'week' и 'month'. В столбцах сохраните порядковые номера недель и месяцев, полученные методами dt.week и dt.month, соответственно.

Недельную воронку сохраните в funnel_weekly. Сгруппируйте данные funnel_daily методом groupby() по столбцу 'week'. Данные столбцов ['impressions', 'clicks', 'registrations'] просуммируйте внутри группировки.

Постройте месячную воронку аналогично недельной. Сохраните в переменной funnel_monthly
В каждой из трёх воронок — дневной, недельной и месячной — посчитайте CTR и CR. Результат сохраните в столбцах 'ctr, %', 'cr, %', соответственно. Выведите на экран месячную воронку.

In [15]:
ad_data = pd.read_csv('./ad_data.csv')
site_data = pd.read_csv('./site_data.csv') 

funnel_daily = ad_data.merge(site_data, on='date')

In [16]:
funnel_daily['date'] = pd.to_datetime(funnel_daily['date']) 
funnel_daily['ctr, %'] = funnel_daily['clicks'] / funnel_daily['impressions'] * 100
funnel_daily['cr, %'] = funnel_daily['registrations'] / funnel_daily['clicks'] * 100

In [17]:
funnel_daily['week'] = funnel_daily['date'].dt.isocalendar().week
# Извлечение номера месяца
funnel_daily['month'] = funnel_daily['date'].dt.month

In [18]:
funnel_weekly = funnel_daily.groupby('week')[['impressions', 'clicks','registrations']].sum()
funnel_monthly = funnel_daily.groupby('month')[['impressions', 'clicks','registrations']].sum()

In [19]:
funnel_weekly['ctr, %'] = funnel_weekly['clicks'] / funnel_weekly['impressions'] * 100
funnel_weekly['cr, %'] = funnel_weekly['registrations'] / funnel_weekly['clicks'] * 100
funnel_monthly['ctr, %'] = funnel_monthly['clicks'] / funnel_monthly['impressions'] * 100
funnel_monthly['cr, %'] = funnel_monthly['registrations'] / funnel_monthly['clicks'] * 100

In [20]:
funnel_weekly.head(5)

      impressions  clicks  registrations    ctr, %     cr, %
week
31          28351     264             23  0.931184  8.712121
32          57031     503             43  0.881976  8.548708
33          57184     471             39  0.823657  8.280255
34          49911     424             37  0.849512  8.726415
35          34956     307             25  0.878247  8.143322

In [21]:
funnel_monthly.head(5)

       impressions  clicks  registrations    ctr, %     cr, %
month
8           227433    1969            167  0.865749  8.481463

### 3 - 1

Проанализируйте продуктовую воронку онлайн-сервиса, помогающего предпринимателям сдавать годовую отчётность. В воронке 3 шага: посещение сайта (pageview), отправка сообщения специалисту компании (chat_message) и оплата (success).

Сохраните логи событий из файла /datasets/funnel_prod_events.csv в переменной events. Сгруппируйте данные переменной events по столбцу event_name и посчитайте количество строк в каждой группе.

Результат сохраните в переменной events_count и выведите её на экран.

In [24]:
events = pd.read_csv('./funnel_prod_events.csv')
events.head()

                   event_time          uid    event_name
0  2019-08-22 03:38:50.902000  96080880366      pageview
1  2019-08-22 05:31:23.893000  96080880366  chat_message
2  2019-08-22 10:20:07.780000  96080880366  chat_message
3  2019-08-22 05:30:49.722000  96080880366      pageview
4  2019-08-22 03:59:04.223000  96080880366  chat_message

In [25]:
events_count = events.groupby('event_name').agg({'uid':'count'})
events_count

               uid
event_name
chat_message  1262
pageview       764
success        510

### 3 - 2

Сгруппируйте данные из переменной events по полю event_name и посчитайте количество уникальных пользователей в каждой группе, применяя метод agg(). Отсортируйте по убыванию.
Результат сохраните в переменной users_count и выведите на экран.

In [28]:
users_count = events.groupby('event_name').agg({'uid':['nunique']}).sort_values(by= ('uid', 'nunique'), ascending=False)
users_count

                 uid
             nunique
event_name
pageview          54
chat_message      43
success           39

### 4 - 2

Проанализируйте воронку интернет-магазина.
Сохраните логи событий из файла /datasets/events.csv в переменной events. Выведите на экран первые 5 строк events, чтобы узнать названия столбцов. Не удаляйте вывод events.
Посчитайте для каждого пользователя самое раннее время наступления каждого события. Результат сохраните в переменной users и выведите на экран первые 5 строк датафрейма.

In [29]:
events = pd.read_csv('./events.csv')
events.head()

  event_name           event_time       uid
0   pageview  2019-08-20 00:27:30  80419792
1   pageview  2019-01-29 08:11:30  74610198
2   pageview  2019-01-29 01:33:02    101714
3   pageview  2019-02-22 19:41:04  90089350
4   pageview  2019-03-04 12:49:09  98247028

In [32]:
users = events.pivot_table(index= 'uid', columns='event_name', values='event_time', aggfunc='min')
users.head()

event_name,add_to_cart,checkout,pageview,payment
uid,,,,
7221,2019-08-04 00:07:52,2019-08-04 00:08:33,2019-08-04 00:07:06,NaN
21371,NaN,NaN,2019-02-21 05:35:16,NaN
31608,2019-08-07 21:14:10,NaN,2019-08-07 21:11:27,NaN
31875,NaN,NaN,2019-04-25 03:16:04,NaN
37099,NaN,NaN,2019-05-09 22:36:09,NaN

### 4 - 2

Посчитайте, сколько пользователей заходили на сайт. Результат сохраните в переменной pageview_count и выведите её на экран.

In [35]:
pageview_count  = users[~users['pageview'].isna()].shape[0]
pageview_count

8831

### 4 - 3


Постройте воронку. Посчитайте:
сколько пользователей добавили товар в корзину после первого захода на сайт;
сколько пользователей начали оформлять заказ после добавления товара в корзину;
сколько из них оплатили заказ после оформления.
Сохраните результаты вычислений в переменных n_add_to_cart, n_checkout и n_payment.

In [36]:
step_1 = ~users['pageview'].isna()
step_2 = step_1 & (users['add_to_cart'] > users['pageview'])
step_3 = step_2 & (users['checkout'] > users['add_to_cart'])
step_4 = step_3 & (users['payment'] > users['checkout'])

In [37]:
n_pageview = users[step_1].shape[0]
n_add_to_cart = users[step_2].shape[0]
n_checkout = users[step_3].shape[0]
n_payment = users[step_4].shape[0]

In [38]:
print('Посетителей:', n_pageview)
print('Добавили товар в корзину:', n_add_to_cart)
print('Начали оформлять заказ:', n_checkout)
print('Оплатили:', n_payment)

Посетителей: 8831
Добавили товар в корзину: 2584
Начали оформлять заказ: 354
Оплатили: 28